# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zd < Formula
  desc "AI agent-friendly CLI for Zendesk"
  homepage "https://github.com/johanviberg/zd"
  version "0.4.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/johanviberg/zd/releases/download/v0.4.12/zd_0.4.12_macOS_x86_64.tar.gz"
      sha256 "0222d4025f8c30d1a89088d66c65d99787d487e90f70b88041bef865495ce952"

      define_method(:install) do
        bin.install "zd"
        bash_completion.install "completions/zd.bash" => "zd"
        zsh_completion.install "completions/zd.zsh" => "_zd"
        fish_completion.install "completions/zd.fish"
        man1.install Dir["manpages/*.1.gz"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/johanviberg/zd/releases/download/v0.4.12/zd_0.4.12_macOS_arm64.tar.gz"
      sha256 "4ecd1d281a6ca8d9599f13bb3154773d9ace541298a4efb9371ba98ab05d4bc3"

      define_method(:install) do
        bin.install "zd"
        bash_completion.install "completions/zd.bash" => "zd"
        zsh_completion.install "completions/zd.zsh" => "_zd"
        fish_completion.install "completions/zd.fish"
        man1.install Dir["manpages/*.1.gz"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/johanviberg/zd/releases/download/v0.4.12/zd_0.4.12_linux_x86_64.tar.gz"
      sha256 "c7911dec01c04f7f37415a5699c13a7d875519f33e7ef0c31bc34ec0b6df9e63"
      define_method(:install) do
        bin.install "zd"
        bash_completion.install "completions/zd.bash" => "zd"
        zsh_completion.install "completions/zd.zsh" => "_zd"
        fish_completion.install "completions/zd.fish"
        man1.install Dir["manpages/*.1.gz"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/johanviberg/zd/releases/download/v0.4.12/zd_0.4.12_linux_arm64.tar.gz"
      sha256 "ec683be0ca7107f900c4ad10d0921902d95112244bf57c14880c2eba454692fe"
      define_method(:install) do
        bin.install "zd"
        bash_completion.install "completions/zd.bash" => "zd"
        zsh_completion.install "completions/zd.zsh" => "_zd"
        fish_completion.install "completions/zd.fish"
        man1.install Dir["manpages/*.1.gz"]
      end
    end
  end

  test do
    system "#{bin}/zd", "version"
  end
end
