# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zd < Formula
  desc "AI agent-friendly CLI for Zendesk"
  homepage "https://github.com/johanviberg/zd"
  version "0.4.15"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/johanviberg/zd/releases/download/v0.4.15/zd_0.4.15_macOS_x86_64.tar.gz"
      sha256 "e5fa912d9999277401fa12cd35925d7ab10c147fdd76ca6e05d4f8f98d36c52f"

      define_method(:install) do
        bin.install "zd"
        bash_completion.install "completions/zd.bash" => "zd"
        zsh_completion.install "completions/zd.zsh" => "_zd"
        fish_completion.install "completions/zd.fish"
        man1.install Dir["manpages/*.1.gz"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/johanviberg/zd/releases/download/v0.4.15/zd_0.4.15_macOS_arm64.tar.gz"
      sha256 "165f3725cf503d86dae0587a893fad2ad66d4cefb790c0037865f33a242990e5"

      define_method(:install) do
        bin.install "zd"
        bash_completion.install "completions/zd.bash" => "zd"
        zsh_completion.install "completions/zd.zsh" => "_zd"
        fish_completion.install "completions/zd.fish"
        man1.install Dir["manpages/*.1.gz"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/johanviberg/zd/releases/download/v0.4.15/zd_0.4.15_linux_x86_64.tar.gz"
      sha256 "beefd8be6c13b69064a7db0dd6f181917cba908af361d18dfe0d921265e0048e"
      define_method(:install) do
        bin.install "zd"
        bash_completion.install "completions/zd.bash" => "zd"
        zsh_completion.install "completions/zd.zsh" => "_zd"
        fish_completion.install "completions/zd.fish"
        man1.install Dir["manpages/*.1.gz"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/johanviberg/zd/releases/download/v0.4.15/zd_0.4.15_linux_arm64.tar.gz"
      sha256 "4ef0df37f82bed30b39ef2cbc9e6c65cd1ffbf8bf8ee9e2fbc78778eddeea763"
      define_method(:install) do
        bin.install "zd"
        bash_completion.install "completions/zd.bash" => "zd"
        zsh_completion.install "completions/zd.zsh" => "_zd"
        fish_completion.install "completions/zd.fish"
        man1.install Dir["manpages/*.1.gz"]
      end
    end
  end

  test do
    system "#{bin}/zd", "version"
  end
end
