# This file was generated by GoReleaser. DO NOT EDIT.
cask "zd" do
  name "zd"
  desc "AI agent-friendly CLI for Zendesk"
  homepage "https://github.com/johanviberg/zd"
  version "0.4.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zd"
  manpage "manpages/zd.1.gz"
  bash_completion "completions/zd.bash"
  zsh_completion "completions/zd.zsh"
  fish_completion "completions/zd.fish"

  on_macos do
    on_intel do
      url "https://github.com/johanviberg/zd/releases/download/v#{version}/zd_#{version}_macOS_x86_64.tar.gz"
      sha256 "2d231b86e6f29adb2f86c5cc6bd8f9bb40c3bb8cc70615a12ef0da2857b90ee5"
    end
    on_arm do
      url "https://github.com/johanviberg/zd/releases/download/v#{version}/zd_#{version}_macOS_arm64.tar.gz"
      sha256 "155af5996233ab82501397383435085701b960186612dc2cd50b625d7b5f1f88"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/johanviberg/zd/releases/download/v#{version}/zd_#{version}_linux_x86_64.tar.gz"
      sha256 "3f4c385d674232a1f47515d28218bb7f459b224328f0e91508ba72ba4bef3575"
    end
    on_arm do
      url "https://github.com/johanviberg/zd/releases/download/v#{version}/zd_#{version}_linux_arm64.tar.gz"
      sha256 "8d803c09801daca1c40310d68c671d3cb7f55551a0ee9446cd0e9b28888d0c2e"
    end
  end

  # No zap stanza required
end
