# This file was generated by GoReleaser. DO NOT EDIT.
cask "zd" do
  name "zd"
  desc "AI agent-friendly CLI for Zendesk"
  homepage "https://github.com/johanviberg/zd"
  version "0.4.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zd"
  manpage "manpages/zd.1.gz"
  bash_completion "completions/zd.bash"
  zsh_completion "completions/zd.zsh"
  fish_completion "completions/zd.fish"

  on_macos do
    on_intel do
      url "https://github.com/johanviberg/zd/releases/download/v#{version}/zd_#{version}_macOS_x86_64.tar.gz"
      sha256 "20f4fd5e6dd4624bc0b8098ef31bd00ddb1f333d77994a38d7d63730d973057b"
    end
    on_arm do
      url "https://github.com/johanviberg/zd/releases/download/v#{version}/zd_#{version}_macOS_arm64.tar.gz"
      sha256 "9f67edfb653645fb23356eff8f027e351c7f9e830e2837e46e7c8e6afbadc31c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/johanviberg/zd/releases/download/v#{version}/zd_#{version}_linux_x86_64.tar.gz"
      sha256 "0779bcddaecf1997e0b2e2c9cf57ff0583da122e51ff677c4cf5844f97097878"
    end
    on_arm do
      url "https://github.com/johanviberg/zd/releases/download/v#{version}/zd_#{version}_linux_arm64.tar.gz"
      sha256 "59983ee06a2f3c0efbfca88fc295da32b31a5b974f5d6d837fb56902943f0544"
    end
  end

  # No zap stanza required
end
