# This file was generated by GoReleaser. DO NOT EDIT.
cask "zd" do
  name "zd"
  desc "AI agent-friendly CLI for Zendesk"
  homepage "https://github.com/johanviberg/zd"
  version "0.4.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zd"
  manpage "manpages/zd.1.gz"
  bash_completion "completions/zd.bash"
  zsh_completion "completions/zd.zsh"
  fish_completion "completions/zd.fish"

  on_macos do
    on_intel do
      url "https://github.com/johanviberg/zd/releases/download/v#{version}/zd_#{version}_macOS_x86_64.tar.gz"
      sha256 "229b98f93362fae5d43fc0f70f3dd5abff724cb006cac540db1bc5c33979b024"
    end
    on_arm do
      url "https://github.com/johanviberg/zd/releases/download/v#{version}/zd_#{version}_macOS_arm64.tar.gz"
      sha256 "7fe1a5de58819f1ecfe9f4af5b2a411d33c3f6bfd0e4c7ff87ad4f49c3af0b89"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/johanviberg/zd/releases/download/v#{version}/zd_#{version}_linux_x86_64.tar.gz"
      sha256 "a15ec0808678756d6cd2e44be09799f80677683e1feeb10639d6e39784a3880c"
    end
    on_arm do
      url "https://github.com/johanviberg/zd/releases/download/v#{version}/zd_#{version}_linux_arm64.tar.gz"
      sha256 "e24cd40642b2fa9ed08411ee63ae5a699c5861b26ec326f487686daba2ebaf83"
    end
  end

  # No zap stanza required
end
